import {Firestore, Timestamp, FieldValue} from 'firebase-admin/firestore';
import {randomBytes} from 'crypto';

const displayName=()=>`Walker-${randomBytes(4).toString('hex').toUpperCase()}`;
async function releaseExpired(db:Firestore,uid:string){
 const ref=db.doc(`matchProfiles/${uid}`); return db.runTransaction(async tx=>{const p=await tx.get(ref),d=p.data(),rid=d?.reservationId;if(d?.matchingStatus!=='reserved'||typeof rid!=='string')return d;
  const rr=db.doc(`matchReservations/${rid}`),r=await tx.get(rr),rd=r.data(); if(!r.exists||rd?.expiresAt?.toMillis()>Date.now())return d;
  tx.set(rr,{status:'expired',expiredAt:Timestamp.now()},{merge:true}); const ids=[rd?.requesterUid,rd?.partnerUid].filter((x):x is string=>typeof x==='string');
  for(const id of ids){const pr=db.doc(`matchProfiles/${id}`),s=await tx.get(pr);if(s.data()?.reservationId===rid)tx.update(pr,{matchingStatus:'available',reservationId:FieldValue.delete(),reservationExpiresAt:FieldValue.delete(),updatedAt:Timestamp.now()});} return undefined;
 });
}
export async function findPartner(db:Firestore,uid:string){
 const meRef=db.doc(`matchProfiles/${uid}`); const me=(await meRef.get()).data(); if(!me) return {status:'no_partner'};
 if(me.activeChallengeId && (await db.doc(`challenges/${me.activeChallengeId}`).get()).data()?.status==='active') return {status:'existing',challengeId:me.activeChallengeId};
 if(me.matchingStatus==='reserved'&&me.reservationId){const reservation=await db.doc(`matchReservations/${me.reservationId}`).get();const rd=reservation.data();if(reservation.exists&&rd?.status==='reserved'&&rd.expiresAt.toMillis()>Date.now()){if(rd.requesterUid===uid){const opponent=await db.doc(`matchProfiles/${rd.partnerUid}`).get();return {status:'reserved',reservationId:me.reservationId,opponentDisplayName:opponent.data()?.publicDisplayName||displayName()};}return {status:'waiting'};}await releaseExpired(db,uid);}
 const now=Timestamp.now(); await meRef.update({matchingStatus:'available',updatedAt:now});
 const snap=await db.collection('matchProfiles').where('matchingStatus','==','available').where('league','==',me.league).where('division','==',me.division).orderBy('lastActiveAt','desc').limit(20).get();
 const candidates=snap.docs.filter(d=>d.id!==uid).map(d=>({ref:d,data:d.data()})).filter(c=>!c.data.lastActiveAt||Date.now()-c.data.lastActiveAt.toMillis()<7*86400000);
 candidates.sort((a,b)=>Math.abs((a.data.recentOfficialSteps??0)-(me.recentOfficialSteps??0))-Math.abs((b.data.recentOfficialSteps??0)-(me.recentOfficialSteps??0))||a.ref.id.localeCompare(b.ref.id));
 const partner=candidates[0]; if(!partner)return {status:'no_partner'};
 const reservationId=db.collection('matchReservations').doc().id; const reservation=db.doc(`matchReservations/${reservationId}`); const expiresAt=Timestamp.fromMillis(now.toMillis()+120000);
 const partnerRef=db.doc(`matchProfiles/${partner.ref.id}`); try { await db.runTransaction(async tx=>{const [mine,other]=await Promise.all([tx.get(meRef),tx.get(partnerRef)]); if(mine.data()?.matchingStatus!=='available'||other.data()?.matchingStatus!=='available') throw new Error('conflict'); tx.create(reservation,{requesterUid:uid,partnerUid:partner.ref.id,createdAt:now,expiresAt,status:'reserved'}); tx.update(meRef,{matchingStatus:'reserved',reservationId,reservationExpiresAt:expiresAt}); tx.update(partnerRef,{matchingStatus:'reserved',reservationId,reservationExpiresAt:expiresAt});}); } catch { return {status:'no_partner'}; }
 return {status:'reserved',reservationId,opponentDisplayName:partner.data.publicDisplayName||displayName()};
}
export async function createChallenge(db:Firestore,a:string,reservationId:string,requestId:string){return db.runTransaction(async tx=>{const dedup=db.doc(`requestDeduplication/${a}/requests/${requestId}`);const old=await tx.get(dedup);if(old.exists){if(old.data()?.operation!=='createChallenge'||typeof old.data()?.challengeId!=='string')throw new Error('request_conflict');const c=await tx.get(db.doc(`challenges/${old.data()!.challengeId}`));if(!c.exists||!(await tx.get(c.ref.collection('participants').doc(a))).exists)throw new Error('request_conflict');return old.data()!.challengeId as string;}const rr=db.doc(`matchReservations/${reservationId}`),r=await tx.get(rr),rd=r.data();if(!r.exists||rd?.requesterUid!==a||rd.status!=='reserved'||rd.expiresAt.toMillis()<=Date.now())throw new Error('invalid_reservation');const ar=db.doc(`matchProfiles/${a}`),br=db.doc(`matchProfiles/${rd.partnerUid}`),[as,bs]=await Promise.all([tx.get(ar),tx.get(br)]);if(!as.exists||!bs.exists||as.data()?.matchingStatus!=='reserved'||bs.data()?.matchingStatus!=='reserved'||as.data()?.reservationId!==reservationId||bs.data()?.reservationId!==reservationId)throw new Error('unavailable');const c=db.collection('challenges').doc(),now=Timestamp.now(),end=Timestamp.fromMillis(now.toMillis()+86400000);tx.set(c,{participantIds:[a,rd.partnerUid],status:'active',timezonePolicy:'participant_local',startedAt:now,endsAt:end,createdAt:now,updatedAt:now});for(const [u,p] of [[a,as.data()],[rd.partnerUid,bs.data()]] as [string,any][])tx.set(c.collection('participants').doc(u),{uid:u,publicDisplayName:p?.publicDisplayName||displayName(),officialSteps:p?.recentOfficialSteps??0,competitionSteps:0,rewardSteps:0,syncState:p?.recentOfficialSteps!=null?'synced':'pending',result:'pending',localDate:p?.localDate||null,timezone:p?.timezone||null,progressUpdatedAt:now});tx.update(ar,{matchingStatus:'matched',activeChallengeId:c.id,reservationId:FieldValue.delete(),reservationExpiresAt:FieldValue.delete(),updatedAt:now});tx.update(br,{matchingStatus:'matched',activeChallengeId:c.id,reservationId:FieldValue.delete(),reservationExpiresAt:FieldValue.delete(),updatedAt:now});tx.update(rr,{status:'consumed',consumedAt:now});tx.create(dedup,{requestId,challengeId:c.id,operation:'createChallenge',createdAt:now,expiresAt:end});return c.id})}
