import {Firestore, Timestamp} from 'firebase-admin/firestore';

const displayName=(uid:string)=>`Walker-${uid.slice(0,4).toUpperCase()}`;
export async function findPartner(db:Firestore,uid:string){
 const meRef=db.doc(`matchProfiles/${uid}`); const me=(await meRef.get()).data(); if(!me) return {status:'no_partner'};
 if(me.activeChallengeId && (await db.doc(`challenges/${me.activeChallengeId}`).get()).data()?.status==='active') return {status:'existing',challengeId:me.activeChallengeId};
 const now=Timestamp.now(); await meRef.update({matchingStatus:'available',updatedAt:now});
 const snap=await db.collection('matchProfiles').where('matchingStatus','==','available').where('league','==',me.league).where('division','==',me.division).orderBy('lastActiveAt','desc').limit(20).get();
 const candidates=snap.docs.filter(d=>d.id!==uid).map(d=>({ref:d,data:d.data()})).filter(c=>!c.data.lastActiveAt||Date.now()-c.data.lastActiveAt.toMillis()<7*86400000);
 candidates.sort((a,b)=>Math.abs((a.data.recentOfficialSteps??0)-(me.recentOfficialSteps??0))-Math.abs((b.data.recentOfficialSteps??0)-(me.recentOfficialSteps??0))||a.ref.id.localeCompare(b.ref.id));
 const partner=candidates[0]; if(!partner)return {status:'no_partner'};
 const reservationId=db.collection('matchReservations').doc().id; await db.doc(`matchReservations/${reservationId}`).set({requesterUid:uid,partnerUid:partner.ref.id,createdAt:now,expiresAt:Timestamp.fromMillis(now.toMillis()+120000),status:'reserved'});
 return {status:'reserved',reservationId,opponentDisplayName:partner.data.publicDisplayName||displayName(partner.ref.id)};
}
export async function createChallenge(db:Firestore,a:string,reservationId:string,requestId:string){return db.runTransaction(async tx=>{const dedup=db.doc(`requestDeduplication/${a}/requests/${requestId}`);const old=await tx.get(dedup);if(old.exists)return old.data()?.challengeId as string;const rr=db.doc(`matchReservations/${reservationId}`),r=await tx.get(rr),rd=r.data();if(!r.exists||rd?.requesterUid!==a||rd.status!=='reserved'||rd.expiresAt.toMillis()<=Date.now())throw new Error('invalid_reservation');const ar=db.doc(`matchProfiles/${a}`),br=db.doc(`matchProfiles/${rd.partnerUid}`),[as,bs]=await Promise.all([tx.get(ar),tx.get(br)]);if(!as.exists||!bs.exists||as.data()?.matchingStatus!=='available'||bs.data()?.matchingStatus!=='available')throw new Error('unavailable');const c=db.collection('challenges').doc(),now=Timestamp.now(),end=Timestamp.fromMillis(now.toMillis()+86400000);tx.set(c,{participantIds:[a,rd.partnerUid],status:'active',timezonePolicy:'participant_local',startedAt:now,endsAt:end,createdAt:now,updatedAt:now});for(const [uid,p] of [[a,as.data()],[rd.partnerUid,bs.data()]] as [string,any][])tx.set(c.collection('participants').doc(uid),{uid,publicDisplayName:p?.publicDisplayName||displayName(uid),officialSteps:p?.recentOfficialSteps??0,competitionSteps:0,rewardSteps:0,syncState:'synced',result:'pending',localDate:p?.localDate||null,timezone:p?.timezone||null,progressUpdatedAt:now});tx.update(ar,{matchingStatus:'matched',activeChallengeId:c.id,updatedAt:now});tx.update(br,{matchingStatus:'matched',activeChallengeId:c.id,updatedAt:now});tx.update(rr,{status:'consumed',consumedAt:now});tx.create(dedup,{requestId,challengeId:c.id,operation:'createChallenge',createdAt:now,expiresAt:end});return c.id})}
