package com.lazyapps.steparena.game

/**
 * Debug-only scenario vocabulary. It lives in the debug source set, so none of these controls
 * can be referenced by or packaged into the release variant.
 */
enum class DebugGameScenario {
    SET_MEASURED_STEPS, COUNTER_100, COUNTER_1000, COUNTER_5000,
    ADD_RECOVERED, ADD_HEALTH_CONNECT, ADD_ESTIMATED, ADD_UNKNOWN, ABNORMAL_STEPS, OVER_30000,
    CREATE_MATCH, SET_NPC_LOW, SET_NPC_HIGH, WIN, LOSS, DRAW, NO_CONTEST,
    FINALIZE, DOUBLE_FINALIZE, RESET_TODAY_MATCH,
    ADD_RATING, REMOVE_RATING, PROMOTION_READY, DEMOTION_READY, PROMOTE, DEMOTE,
    THREE_WIN_STREAK, FIVE_WIN_STREAK, THREE_LOSS_STREAK, END_BEGINNER_PERIOD,
    LEAGUE_CREATE, LEAGUE_FIRST, LEAGUE_FIFTH, LEAGUE_TENTH, LEAGUE_FINALIZE,
    MONTH_END, SEASON_FINALIZE, NEXT_SEASON,
    FIRST_STEP_ACHIEVEMENT, FIRST_WIN_ACHIEVEMENT, EVALUATE_ACHIEVEMENTS,
    DUPLICATE_ACHIEVEMENT, RESET_ACHIEVEMENTS,
    NEXT_DAY, NEXT_WEEK, NEXT_MONTH, CHANGE_TIME_ZONE, CLOCK_ROLLBACK,
    SAME_DAY_REPROCESS, RERUN_WORK_MANAGER, RESET_DEBUG_DATA,
}
